#!/bin/bash

. /etc/default/playsms

while true
do
    killall -9 smsd >/dev/null 2>&1
    sleep 3
    CWD=`pwd`
    cd $PLAYSMS_LOG
    nohup /usr/sbin/smsd -m file -c $PLAYSMS_SPOOL -u $PLAYSMS_BIN/gnokii_smsd_incoming -f $PLAYSMS_LOG/gnokii_smsd_logs >/dev/null 2>&1 &
    cd $CWD
    sleep 16m
done
