#!/bin/sh
# Start/stop the playsms service

# This is the default init.d script for Playsms.

# Make sure that the Playsms binaries can be found in $BOXPATH or somewhere
# else along $PATH.  run_playsms_box has to be in $BOXPATH.

### BEGIN INIT INFO
# Provides:          playsms
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Should-Start:      $network $named
# Should-Stop:       $network $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: playSMS SMS gateway daemon
# Description:       playSMS is a platform to manage other sms backends
#		     to send and receive sms
### END INIT INFO

. /lib/lsb/init-functions

DAEMON=$(which playsmsd)

if [ ! -x $DAEMON ]; then
	log_failure_msg "Unable to find and run playsmsd"
	exit 1
fi

case "$1" in
  start)
    log_daemon_msg "Starting playsms daemon"
    log_progress_msg "playsmsd"
    $DAEMON start >/dev/null 2>&1
    log_end_msg 0
    ;;

  stop)
    log_daemon_msg "Stopping playsms daemon"
    log_progress_msg "playsms"
    $DAEMON stop >/dev/null 2>&1
    log_end_msg 0
    ;;

  status)
    RUNNING=`ps uf -C playsmsd | grep schedule`
    if [ -n "$RUNNING" ]; then
	log_daemon_msg "playsmsd is running"
    else
	log_failure_msg "playsmsd is not running"
    fi
    ;;

  reload|restart|force-reload)
    $0 stop
    sleep 2
    $0 start
    ;;

  *)
    echo "Usage: $0 {status|start|stop|restart}"
    exit 1

esac

exit 0
