#!/bin/sh
#!/bin/bash
# playsms daemon
# chkconfig: 3456 20 80
# description: playsms daemon
# processname: playsms

PLAYSMS_BIN=/usr/local/bin

# DO NOT CHANGE BELOW THIS LINE

. /lib/lsb/init-functions

DAEMON=$PLAYSMS_BIN/playsmsd

if [ ! -x $DAEMON ]; then
	echo "[ERROR] Unable to find and run playsmsd"
	exit 1
fi

case "$1" in
  start)
    echo -n "Starting playsms daemon"
    $DAEMON start >/dev/null 2>&1
    echo " [OK]"
    ;;

  stop)
    echo -n "Stopping playsms daemon"
    $DAEMON stop >/dev/null 2>&1
    echo " [OK]"
    ;;

  status)
    RUNNING=`ps uf -C playsmsd | grep schedule`
    if [ -n "$RUNNING" ]; then
	echo "playsmsd is running"
    else
	echo "playsmsd is not running"
    fi
    ;;

  reload|restart|force-reload)
    $0 stop
    sleep 2
    $0 start
    ;;

  *)
    echo "Usage: $0 {status|start|stop|restart}"
    exit 1

esac

exit 0
