TRUNCATE playsms_tblCountry;
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('af','Afghanistan','93');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('al','Albania','355');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('dz','Algeria','213');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ad','Andorra','376');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ao','Angola','244');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('aq','Antarctica','672');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ar','Argentina','54');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('am','Armenia','374');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('aw','Aruba','297');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('au','Australia','61');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('at','Austria','43');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('az','Azerbaijan','994');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('bh','Bahrain','973');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('bd','Bangladesh','880');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('by','Belarus','375');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('be','Belgium','32');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('bz','Belize','501');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('bj','Benin','229');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('bt','Bhutan','975');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('bo','Bolivia, Plurinational State Of','591');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ba','Bosnia And Herzegovina','387');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('bw','Botswana','267');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('br','Brazil','55');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('bn','Brunei Darussalam','673');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('bg','Bulgaria','359');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('bf','Burkina Faso','226');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('mm','Myanmar','95');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('bi','Burundi','257');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('kh','Cambodia','855');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('cm','Cameroon','237');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ca','Canada','1');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('cv','Cape Verde','238');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('cf','Central African Republic','236');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('td','Chad','235');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('cl','Chile','56');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('cn','China','86');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('cx','Christmas Island','61');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('cc','Cocos (keeling) Islands','61');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('co','Colombia','57');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('km','Comoros','269');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('cg','Congo','242');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('cd','Congo, The Democratic Republic Of The','243');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ck','Cook Islands','682');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('cr','Costa Rica','506');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('hr','Croatia','385');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('cu','Cuba','53');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('cy','Cyprus','357');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('cz','Czech Republic','420');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('dk','Denmark','45');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('dj','Djibouti','253');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('tl','Timor-leste','670');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ec','Ecuador','593');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('eg','Egypt','20');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('sv','El Salvador','503');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('gq','Equatorial Guinea','240');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('er','Eritrea','291');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ee','Estonia','372');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('et','Ethiopia','251');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('fk','Falkland Islands (malvinas)','500');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('fo','Faroe Islands','298');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('fj','Fiji','679');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('fi','Finland','358');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('fr','France','33');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('pf','French Polynesia','689');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ga','Gabon','241');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('gm','Gambia','220');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ge','Georgia','995');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('de','Germany','49');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('gh','Ghana','233');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('gi','Gibraltar','350');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('gr','Greece','30');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('gl','Greenland','299');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('gt','Guatemala','502');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('gn','Guinea','224');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('gw','Guinea-bissau','245');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('gy','Guyana','592');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ht','Haiti','509');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('hn','Honduras','504');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('hk','Hong Kong','852');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('hu','Hungary','36');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('in','India','91');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('id','Indonesia','62');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ir','Iran, Islamic Republic Of','98');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('iq','Iraq','964');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ie','Ireland','353');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('im','Isle Of Man','44');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('il','Israel','972');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('it','Italy','39');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ci','Côte D\'ivoire','225');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('jp','Japan','81');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('jo','Jordan','962');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('kz','Kazakhstan','7');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ke','Kenya','254');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ki','Kiribati','686');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('kw','Kuwait','965');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('kg','Kyrgyzstan','996');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('la','Lao People\'s Democratic Republic','856');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('lv','Latvia','371');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('lb','Lebanon','961');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ls','Lesotho','266');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('lr','Liberia','231');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ly','Libya','218');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('li','Liechtenstein','423');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('lt','Lithuania','370');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('lu','Luxembourg','352');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('mo','Macao','853');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('mk','Macedonia, The Former Yugoslav Republic Of','389');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('mg','Madagascar','261');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('mw','Malawi','265');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('my','Malaysia','60');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('mv','Maldives','960');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ml','Mali','223');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('mt','Malta','356');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('mh','Marshall Islands','692');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('mr','Mauritania','222');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('mu','Mauritius','230');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('yt','Mayotte','262');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('mx','Mexico','52');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('fm','Micronesia, Federated States Of','691');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('md','Moldova, Republic Of','373');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('mc','Monaco','377');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('mn','Mongolia','976');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('me','Montenegro','382');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ma','Morocco','212');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('mz','Mozambique','258');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('na','Namibia','264');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('nr','Nauru','674');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('np','Nepal','977');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('nl','Netherlands','31');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('nc','New Caledonia','687');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('nz','New Zealand','64');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ni','Nicaragua','505');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ne','Niger','227');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ng','Nigeria','234');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('nu','Niue','683');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('kp','Korea, Democratic People\'s Republic Of','850');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('no','Norway','47');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('om','Oman','968');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('pk','Pakistan','92');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('pw','Palau','680');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('pa','Panama','507');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('pg','Papua New Guinea','675');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('py','Paraguay','595');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('pe','Peru','51');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ph','Philippines','63');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('pn','Pitcairn','870');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('pl','Poland','48');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('pt','Portugal','351');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('pr','Puerto Rico','1');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('qa','Qatar','974');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ro','Romania','40');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ru','Russian Federation','7');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('rw','Rwanda','250');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('bl','Saint Barthélemy','590');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ws','Samoa','685');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('sm','San Marino','378');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('st','Sao Tome And Principe','239');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('sa','Saudi Arabia','966');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('sn','Senegal','221');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('rs','Serbia','381');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('sc','Seychelles','248');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('sl','Sierra Leone','232');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('sg','Singapore','65');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('sk','Slovakia','421');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('si','Slovenia','386');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('sb','Solomon Islands','677');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('so','Somalia','252');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('za','South Africa','27');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('kr','Korea, Republic Of','82');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('es','Spain','34');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('lk','Sri Lanka','94');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('sh','Saint Helena, Ascension And Tristan Da Cunha','290');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('pm','Saint Pierre And Miquelon','508');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('sd','Sudan','249');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('sr','Suriname','597');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('sz','Swaziland','268');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('se','Sweden','46');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ch','Switzerland','41');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('sy','Syrian Arab Republic','963');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('tw','Taiwan, Province Of China','886');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('tj','Tajikistan','992');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('tz','Tanzania, United Republic Of','255');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('th','Thailand','66');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('tg','Togo','228');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('tk','Tokelau','690');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('to','Tonga','676');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('tn','Tunisia','216');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('tr','Turkey','90');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('tm','Turkmenistan','993');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('tv','Tuvalu','688');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ae','United Arab Emirates','971');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ug','Uganda','256');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('gb','United Kingdom','44');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ua','Ukraine','380');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('uy','Uruguay','598');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('us','United States','1');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('uz','Uzbekistan','998');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('vu','Vanuatu','678');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('va','Holy See (vatican City State)','39');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ve','Venezuela, Bolivarian Republic Of','58');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('vn','Viet Nam','84');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('wf','Wallis And Futuna','681');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('ye','Yemen','967');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('zm','Zambia','260');
INSERT INTO playsms_tblCountry (country_code, country_name, country_prefix) VALUES ('zw','Zimbabwe','263');
