#!/usr/bin/php -q
<?php

$playsms_conf_file = "/etc/default/playsms";

if (file_exists($playsms_conf_file)) {
	$conf = parse_ini_file($playsms_conf_file);
	$playsms_path = trim($conf['PLAYSMS_PATH']);
	if (is_dir($playsms_path) && file_exists($playsms_path."/init.php")) {
		chdir($playsms_path);
		include "init.php";
		$db_query = "SELECT uid,username,password FROM "._DB_PREF_."_tblUser";
		$db_result = dba_query($db_query);
		while ($db_row = dba_fetch_array($db_result)) {
			$c_uid = $db_row['uid'];
			$c_username = $db_row['username'];
			$c_password = $db_row['password'];
			if (strlen($c_password)!=32) {
				$db_query2 = "UPDATE "._DB_PREF_."_tblUser SET password='".md5($c_password)."' WHERE uid='".$c_uid."'";
				if ($db_result2 = dba_affected_rows($db_query2)) {
					echo "user: [".$c_username."] password has been converted to md5 format\n";
				}
			} else {
				echo "user: [".$c_username."] password most likely already in md5 format\n";
			}
		}
	}
} else {
	echo "ERROR: playSMS config file (/etc/default/playsms) not found";
}

?>